# Generated by Django 6.0 on 2025-12-04 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epf', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ppf', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('nps', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('bank_savings', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_investments', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('equity_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('mutual_funds_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('gold_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crypto_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('other_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('emergency_fund', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('loan_emis', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('investment_sips', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('misc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('term', models.CharField(choices=[('short_term', 'Short Term'), ('medium_term', 'Medium Term'), ('long_term', 'Long Term')], max_length=20, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('monthly_debt_contribution', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RetirementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_retirement_age', models.IntegerField(blank=True, null=True)),
                ('retirement_lifestyle_description', models.TextField(blank=True, null=True)),
                ('desired_retirement_expenses_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_tolerance_score', models.IntegerField(blank=True, null=True)),
                ('investment_preferences', models.TextField(blank=True, null=True)),
                ('annual_savings_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('risk_appetite', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
